use_frameworks!

platform :ios, '9.0'

target 'FlaneurImagePicker_Example' do
  pod 'FlaneurImagePicker', :path => '../'

  target 'FlaneurImagePicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
