# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild clean -workspace Example/FlaneurImagePicker.xcworkspace -scheme FlaneurImagePicker-Example | xcpretty
  - set -o pipefail && xcodebuild -workspace Example/FlaneurImagePicker.xcworkspace -scheme FlaneurImagePicker-Example | xcpretty
  - set -o pipefail && xcodebuild test -workspace Example/FlaneurImagePicker.xcworkspace -scheme FlaneurImagePicker-Example -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 7' -enableCodeCoverage YES | xcpretty
  - pod lib lint --allow-warnings
