//
//  FlaneurImagePickerError.swift
//  FlaneurImagePicker
//
//  Created by Mickaël Floc'hlay on 20/11/2017.
//

import Foundation

/// Errors that can be generated by this framework.
public enum FlaneurImagePickerError: LocalizedError {
    /// Used to track errors happening in the empty view management.
    case emptyViewError(String)
}
