/// Errors that can be generated by this framework.
public enum FlaneurImagePickerError: LocalizedError {
    /// Used to track errors happening in the empty view management.
    case emptyViewError(String)
}
